"""empty message

Revision ID: 83b4dafd7a5e
Revises: 7bc33ee704e2
Create Date: 2020-01-16 22:31:06.768327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b4dafd7a5e'
down_revision = '7bc33ee704e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('education_basis', sa.Enum('nan', 'budget', 'contract', name='educationbasis'), nullable=False))
    op.add_column('user', sa.Column('education_degree', sa.Enum('nan', 'bachelor', 'specialist', 'master', name='educationdegree'), nullable=False))
    op.add_column('user', sa.Column('education_form', sa.Enum('nan', 'full_time', 'distance', 'evening', name='educationform'), nullable=False))
    op.add_column('user', sa.Column('entrance_year', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    op.drop_column('user', 'entrance_year')
    op.drop_column('user', 'education_form')
    op.drop_column('user', 'education_degree')
    op.drop_column('user', 'education_basis')
    # ### end Alembic commands ###
